apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pharmacy-ingress
  namespace: pharmacy-app
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.datlaid.com
    secretName: pharmacy-app
  rules:
  - host: demo.datlaid.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end-service
            port:
              name: http-fe
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: back-end-service
            port:
              name: http-be
tls:
- hosts:
  - demo.datlaid.com
  secretName: ssl-demo.datlaid.com
